---
# tasks file for jenkins
- name: Installing boto.
  pip:
    name: boto

- name: Launch instance
  ec2:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    key_name: "{{ keypair }}"
    id: "{{ id }}"
    group_id: "{{ security_group }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    user_data: |
      #!/bin/bash
      yum install wget vim -y
      yum install epel-release -y
      yum install ansible git bcrypt -y
      wget -O- https://get.docker.com/ | sh
      systemctl status docker
      systemctl start docker
      systemctl enable docker
      systemctl status docker
      systemctl status -l docker
      yum install -y docker-compose
      ansible-galaxy install geerlingguy.nginx
      ansible-galaxy install geerlingguy.jenkins
      wget -O nginx.yaml https://gist.github.com/hemanth22/d3b7fd2693c5d2d44804d420f79bfb18/raw
      ansible-playbook nginx.yaml
      wget -O /root/.ansible/roles/geerlingguy.jenkins/molecule/default/jenkins.yml https://gist.github.com/hemanth22/3b0970dc0c24efd9261bbac304ba9dc2/raw
      ansible-playbook /root/.ansible/roles/geerlingguy.jenkins/molecule/default/jenkins.yml
      usermod -a -G docker jenkins
      wget -O jenkins_config.yaml https://gist.github.com/hemanth22/0b7d71fe3fab06bf2dbb5536f3f2013e/raw
      ansible-playbook jenkins_config.yaml
    wait: true
    wait_timeout: 500
    instance_tags:
      Name: Jenkins
      Environment: Production
    region: "{{ region }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: "{{ volume_size }}"
        delete_on_termination: true
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    assign_public_ip: true
    count_tag:
      Name: Jenkins
    exact_count: 1
  register: ec2

- name: Add new instance to host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: launched
  loop: "{{ ec2.instances }}"
